# https://support.circleci.com/hc/en-us/articles/360006735753-Validating-your-CircleCI-Configuration

version: 2.1
references:

  build_image: &build_image
    run:
      name: Build Docker Image
      command: |
        echo $IMAGE && echo $PYTHON
        docker build -t $IMAGE:py${PYTHON/./} -f Dockerfile --build-arg PYTHON_VERSION=$PYTHON .

  test_image: &test_image
    run:
      name: Sample image run
      command: |
        docker image ls
        docker run -i -t $IMAGE:py${PYTHON/./} python -c "import sys; print(sys.version)"

  publish_image: &publish_image
    run:
      name: Publish Image to Docker Hub
      command: |
        # push only if the DOCKERHUB credentials are given
        # also limit pushes only from master branch - like "$CIRCLE_BRANCH" != "devel"
        if [[ "$DOCKERHUB_USERNAME" != "" && "$CIRCLE_BRANCH" == "master" ]]; then
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          # docker tag local-image:tagname user-name/new-repo:tagname
          docker tag $IMAGE:py${PYTHON/./} $DOCKERHUB_USERNAME/docker_sample:py${PYTHON/./}
          # docker push user-name/new-repo:tagname
          docker push $DOCKERHUB_USERNAME/docker_sample
        fi

jobs:
  dockers:
    parameters:
      python:
        type: string
    machine: true
    environment:
      - IMAGE: "ubuntu"
      - PYTHON: << parameters.python >>
    steps:
      - checkout
      - *build_image
      - *test_image
      - *publish_image

workflows:
  build-dockers:
    jobs:
      - dockers:
          matrix:
            parameters:
              python: ["2.7", "3.8"]